name: First GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Show system information
        run: |
          echo "Operating System:"
          uname -a

          echo "Current user:"
          whoami

          echo "Current directory:"
          pwd
